/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/HoleStar.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Glass_Connector_0929080957.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/HoleStar.glb");
